from typing import Dict, List, Any, Optional

from rest_framework.generics import GenericAPIView
from rest_framework.response import Response


class FancyListApiView(GenericAPIView):
    """Implements an API List view to use for FancyList lists.

    Spits out data in the format used by the FancyList constructor method
    """
    class SortDefinition:
        """Defines a sort option for a field

        Field should be given as a string, in the format
        {attribute}(.{subattribute})*

        (read, just like you would access an attribute of an object in Python,
        but sans the object itself and as a string).

        For example:
        "subObject.title"

        :param {str} field: the field that is sortable
        :param {str} label: The text to display in the dropdown. Direction
               arrows are added automatically
        :param {"asc"|"desc"|None} default: If not None, this direction will be
               the sort applied upon load. If multiple defs are set as default,
               the first one encountered will be used
        :param {bool} asc: whether sorting ascendingly is supported
        :param {bool} desc: whether sorting descendingly is supported
        """
        def __init__(
                self,
                field: str,
                label: str,
                default: Optional[str] = None,
                asc: bool = True,
                desc: bool = True,
        ):
            self.field = field
            self.label = label
            self.asc = asc
            self.desc = desc
            self.default = default

        def serialize(self):
            return {
                'label': self.label,
                'asc': self.asc,
                'desc': self.desc,
                'default': self.default,
            }

    class FilterDefinition:
        """Defines a filter for a field.

        Options for a filter are automatically generated by Vue

        Field should be given as a string, in the format
        {attribute}(.{subattribute})*

        (read, just like you would access an attribute of an object in Python,
        but sans the object itself and as a string).

        For example:
        "subObject.created"

        :param {str} field: the field that is sortable
        :param {str} display_name: Text that should be displayed on the button
        """
        def __init__(self, field, display_name):
            self.field = field
            self.display_name = display_name

    searchable_fields = []
    sort_definitions = []
    filter_definitions = []
    context = {}
    num_items_options = [5, 10, 25, 50]

    def get(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())

        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = self.get_serializer(queryset, many=True)

        return Response({
            'items': serializer.data,
            'context': self.get_context(),
            'searchableFields': self.get_searchable_fields(),
            'filterDefinitions': self._get_filter_definitions(),
            'numItemsOptions': self.get_num_items_options(),
            'sortDefinitions': self._get_sort_definitions(),
        })

    def get_searchable_fields(self) -> List[str]:
        """Returns a list of path strings of fields that can be searched
        through.

        If an empty list is returned, all fields are searchable
        """
        return self.searchable_fields

    def get_sort_definitions(self) -> List['SortDefinition']:
        """Returns a list of sort definitions. See SortDefinition for more info.

        If an empty list is returned, the sort box will be hidden and the
        sort of the QuerySet is used.
        """
        return self.sort_definitions

    def _get_sort_definitions(self) -> Dict[str, Dict]:
        """Serializes get_sort_definitions"""
        return {x.field: x.serialize() for x in self.get_sort_definitions()}

    def get_context(self) -> Dict[str, Any]:
        """Returns any data accessible by all items in the Vue template"""
        return self.context

    def get_num_items_options(self) -> List[int]:
        """Returns the possible items per page options"""
        return self.num_items_options

    def get_filter_definitions(self) -> List['FilterDefinition']:
        """Returns a list of filter definitions. See FilterDefinition for more
        info.

        If an empty list is returned, filters will be disabled.
        """
        return self.filter_definitions

    def _get_filter_definitions(self) -> Dict[str, str]:
        """Serializes get_filter_definitions"""
        return {x.field: x.display_name for x in self.get_filter_definitions()}

