# Generated by Django 4.0.7 on 2023-01-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_integration_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='name',
        ),
    ]
