# Generated by Django 4.0.8 on 2023-08-11 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_vue', '0002_exampledata_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampledata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
