# Generated by Django 4.0.8 on 2023-08-04 09:59

import cdh.core.fields.month_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthFieldTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_month_field', cdh.core.fields.month_fields.MonthField(blank=True, null=True)),
                ('single_month_field', cdh.core.fields.month_fields.MonthField(blank=True, null=True, validators=[cdh.core.fields.month_fields.MinYearValidator(2000), cdh.core.fields.month_fields.MaxYearValidator(2038)])),
            ],
        ),
    ]
