# Generated by Django 3.2.6 on 2021-09-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='field_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
