# Generated by Django 5.2.13 on 2026-05-01 12:52

import cdh.files.db.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_auto_20210921_1014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="uuid",
            field=cdh.files.db.models.MySQLSafeUUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Universally Unique IDentifier",
            ),
        ),
    ]
