# Generated by Django 3.2.7 on 2021-10-04 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uil.files.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0004_auto_20210921_1014'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', uil.files.db.fields.TrackedFileField(to='files.File')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedCustomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', uil.files.db.fields.TrackedFileField(to='dev_files.CustomFile')),
            ],
        ),
        migrations.CreateModel(
            name='SingleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nullable_file', uil.files.db.fields.FileField(blank=True, filename_generator=uil.files.db.fields._default_filename_generator, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.file')),
                ('required_file', uil.files.db.fields.FileField(filename_generator=uil.files.db.fields._default_filename_generator, on_delete=django.db.models.deletion.CASCADE, to='files.file')),
            ],
        ),
        migrations.CreateModel(
            name='CustomSingleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nullable_file', uil.files.db.fields.FileField(blank=True, filename_generator=uil.files.db.fields._default_filename_generator, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev_files.customfile')),
                ('required_file', uil.files.db.fields.FileField(filename_generator=uil.files.db.fields._default_filename_generator, on_delete=django.db.models.deletion.CASCADE, to='dev_files.customfile')),
            ],
        ),
    ]
